### ISSUE TITLE
On long running jobs (>1h) sometimes the output is lost

### ISSUE THREAD

**Issue by mvintila** [syscollective/saltpeter#4]
Some long-running jobs experience some sort of timeout and the output of the job is lost.

The job continues to run and finishes correctly, though.

This might be fixed by upgrading Salt.

**Comment by mvintila** [comment]
Still occurs using latest Salt at this date.

**Comment by mvintila** [comment]
Uppon further investigation the following have been found:

- The salt minion handles the process correctly, it does track it for it's whole duration, logging the start and the end of the process at the correct times
- At some point after about 1h10m, in some cases, not always, the salt-master stops asking about the job. This normally happens every 10 seconds
- There is a hardcoded parameter for event.get_event in https://github.com/saltstack/salt/blob/4f3cb36955d84c6793efcbeabf53963067922d90/salt/client/__init__.py#L1033 . Might be worth a try to increase this.
- There is a parameter called gather_job_timeout that might be worth setting in cmd_iter invocation

**Comment by mvintila** [comment]
Further points:
- Setting auto_reconnect parameter for salt.client.LocalClient
- Further follow the code in get_iter_returns: https://github.com/saltstack/salt/blob/4f3cb36955d84c6793efcbeabf53963067922d90/salt/client/__init__.py#L1055

**Comment by mvintila** [comment]
Ran a 2h sleep test with salt 3005.1 running on localhost minion - did not reproduce.

**Comment by mvintila** [comment]
Potentially fixed.

**Comment by bishop0001** [comment]
This is text that will not be changed
OLD <<<<
Still occurs using latest Salt at this date.
>>>> OLD
NEW <<<<
I think I have a fix for this.
>>>> NEW

**Comment by bishop0001** [comment]
I think I have a fix for this.
